import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const projectRoot = path.resolve(import.meta.dirname, "..");
const sourcePath = path.join(projectRoot, "content", "talk.ru.md");
const referencesPath = path.join(projectRoot, "content", "references.json");
const outputPath = path.join(projectRoot, "content", "generated.ts");

function parseFrontMatter(block) {
  const match = block.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) {
    throw new Error("Every slide must start with YAML-like front matter");
  }

  const metadata = {};
  for (const rawLine of match[1].split("\n")) {
    const separator = rawLine.indexOf(":");
    if (separator < 0) continue;
    const key = rawLine.slice(0, separator).trim();
    const value = rawLine.slice(separator + 1).trim();
    metadata[key] = key === "minutes" ? Number(value) : value;
  }

  const [body, notes = ""] = match[2].split("\n<!-- notes -->\n");
  return {
    ...metadata,
    body: body.trim(),
    notes: notes.trim(),
  };
}

const [source, referencesRaw] = await Promise.all([
  readFile(sourcePath, "utf8"),
  readFile(referencesPath, "utf8"),
]);

const slides = source
  .split(/\n===\n/g)
  .map((block) => block.trim())
  .filter(Boolean)
  .map(parseFrontMatter);

const references = JSON.parse(referencesRaw);
const referenceIds = new Set(references.map((reference) => reference.id));
const slideIds = new Set();

for (const slide of slides) {
  for (const required of ["id", "section", "title", "visual", "minutes"]) {
    if (!slide[required]) {
      throw new Error(`Slide ${slide.id ?? "<unknown>"} misses ${required}`);
    }
  }
  if (slideIds.has(slide.id)) {
    throw new Error(`Duplicate slide id: ${slide.id}`);
  }
  slideIds.add(slide.id);

  const citations = `${slide.body}\n${slide.notes}`.matchAll(/\[(\d+)\]/g);
  for (const citation of citations) {
    const id = Number(citation[1]);
    if (!referenceIds.has(id)) {
      throw new Error(`Slide ${slide.id} cites unknown source [${id}]`);
    }
  }
}

const totalMinutes = slides.reduce((sum, slide) => sum + slide.minutes, 0);
if (totalMinutes > 42) {
  throw new Error(`Core talk is too long: ${totalMinutes} minutes`);
}

const output = `// Generated by scripts/build-content.mjs. Edit content/talk.ru.md instead.
export const slides = ${JSON.stringify(slides, null, 2)} as const;
export const references = ${JSON.stringify(references, null, 2)} as const;
export const talkMeta = ${JSON.stringify(
  { totalMinutes, slideCount: slides.length },
  null,
  2,
)} as const;
`;

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, output);
console.log(`Generated ${slides.length} slides (${totalMinutes} min)`);
