import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const projectRoot = path.resolve(import.meta.dirname, "..");
const outputPath = path.join(projectRoot, "content", "generated.ts");

function parseFrontMatter(block) {
  const match = block.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) {
    throw new Error("Every slide must start with YAML-like front matter");
  }

  const metadata = {};
  for (const rawLine of match[1].split("\n")) {
    const separator = rawLine.indexOf(":");
    if (separator < 0) continue;
    const key = rawLine.slice(0, separator).trim();
    const value = rawLine.slice(separator + 1).trim();
    metadata[key] = key === "minutes" ? Number(value) : value;
  }

  const [body, notes = ""] = match[2].split(/\n?<!-- notes -->\n/);
  return {
    ...metadata,
    body: body.trim(),
    notes: notes.trim(),
  };
}

async function buildLanguage(language) {
  const [source, bonusSource, referencesRaw] = await Promise.all([
    readFile(path.join(projectRoot, "content", `talk.${language}.md`), "utf8"),
    readFile(path.join(projectRoot, "content", `bonus-transformer.${language}.md`), "utf8"),
    readFile(path.join(projectRoot, "content", language === "ru" ? "references.json" : "references.en.json"), "utf8"),
  ]);

  const allSlides = `${source}\n===\n${bonusSource}`
    .split(/\n===\n/g)
    .map((block) => block.trim())
    .filter(Boolean)
    .map(parseFrontMatter);

  const references = JSON.parse(referencesRaw);
  const referenceIds = new Set(references.map((reference) => reference.id));
  const slideIds = new Set();

  for (const slide of allSlides) {
    for (const required of ["id", "section", "visual", "minutes"]) {
      if (!slide[required]) {
        throw new Error(`Slide ${slide.id ?? "<unknown>"} misses ${required}`);
      }
    }
    if (slideIds.has(slide.id)) {
      throw new Error(`Duplicate slide id: ${slide.id}`);
    }
    slideIds.add(slide.id);

    const citations = `${slide.body}\n${slide.notes}`.matchAll(/\[(\d+)\]/g);
    for (const citation of citations) {
      const id = Number(citation[1]);
      if (!referenceIds.has(id)) {
        throw new Error(`Slide ${slide.id} cites unknown source [${id}]`);
      }
    }
  }

  const slides = allSlides.filter((slide) => slide.track !== "bonus");
  const bonusSlides = allSlides.filter((slide) => slide.track === "bonus");
  const totalMinutes = slides.reduce((sum, slide) => sum + slide.minutes, 0);
  const bonusMinutes = bonusSlides.reduce((sum, slide) => sum + slide.minutes, 0);
  if (totalMinutes > 65) {
    throw new Error(`Core talk is too long: ${totalMinutes} minutes`);
  }

  return {
    slides,
    bonusSlides,
    references,
    talkMeta: {
      title: slides[0].title ?? slides[0].kicker ?? (language === "ru" ? "Презентация" : "Presentation"),
      description: slides[0].subtitle ?? slides[0].body.split("\n")[0],
      kicker: slides[0].kicker ?? "",
      brand: slides[0].brand ?? "LLM / AGENTS",
      totalMinutes,
      slideCount: slides.length,
      bonusMinutes,
      bonusSlideCount: bonusSlides.length,
    },
  };
}

const [ru, en] = await Promise.all([buildLanguage("ru"), buildLanguage("en")]);

const output = `// Generated by scripts/build-content.mjs. Edit the locale source files instead.
export const contentByLanguage = ${JSON.stringify({ ru, en }, null, 2)} as const;
export const slides = contentByLanguage.ru.slides;
export const bonusSlides = contentByLanguage.ru.bonusSlides;
export const references = contentByLanguage.ru.references;
export const talkMeta = contentByLanguage.ru.talkMeta;
`;

await mkdir(path.dirname(outputPath), { recursive: true });
await writeFile(outputPath, output);
console.log(
  `Generated RU/EN: ${ru.slides.length} core slides (${ru.talkMeta.totalMinutes} min) + ${ru.bonusSlides.length} bonus slides (${ru.talkMeta.bonusMinutes} min)`,
);
